crs:
  src: epsg:4326
  dst: epsg:32719

xy_units:
  src: deg
  dst: km

depth:
  src_units: km
  src_positive: down
  dst_units: km
  dst_positive: up

input:
  file: ../data/cat_slab_interface.csv
  columns: [longitude, latitude, depth]
  lon_range: [-75.5, -60.0]
  lat_range: [-22.5, -18.0]
  depth_range_km: [0, 70]

output:
  format: vtp
  file: ./earthquakes_interface.vtp